route:
    receiver: "email"

receivers:
    - name: "email"
      email_configs:
          - send_resolved: true
            to: $ADMIN_EMAIL
            from: admin@$PRIMARY_DOMAIN_NAME
            smarthost: $PRIMARY_DOMAIN_NAME:587
            hello: $PRIMARY_DOMAIN_NAME
            auth_username: admin
            auth_password: $ADMIN_PWD
