include:
    # Auto devop
    - template: Auto-DevOps.gitlab-ci.yml
    # Image build script
    - project: flap-box/flap
      file: build_image.yml

variables:
    VERSION_SCRIPT: cat ./system/scripts/migrations/base_migration.txt
    GIT_SUBMODULE_STRATEGY: recursive

system_test:
    stage: test
    image: docker:stable
    services: ["docker:dind"]
    script:
        # Delete container when it exit
        # Bind docker.sock so we can get around dind limitations when binding volumes and use docker
        # Set env var for FLAP_DIR to map with the host filesystem
        # Bind $FLAP_DATA to save wathever operation is done
        - >
            docker run \
                --rm \
                --volume /var/run/docker.sock:/var/run/docker.sock \
                --volume $CI_PROJECT_DIR:$CI_PROJECT_DIR \
                --env FLAP_DIR=$CI_PROJECT_DIR \
                --volume /flap:/flap \
                --env FLAP_DATA=/flap \
                $CI_REGISTRY_IMAGE:$(eval $VERSION_SCRIPT) \
                $CI_PROJECT_DIR/system/scripts/start_flap.sh
        - >
            docker run \
                --rm \
                --volume /var/run/docker.sock:/var/run/docker.sock \
                --volume $CI_PROJECT_DIR:$CI_PROJECT_DIR \
                --env FLAP_DIR=$CI_PROJECT_DIR \
                --volume /flap:/flap \
                --env FLAP_DATA=/flap \
                $CI_REGISTRY_IMAGE:$(eval $VERSION_SCRIPT) \
                manager test setup tls

integration_test:
    stage: test
    script:
        - echo "OK"
