include:
    # Auto devop
    - template: Auto-DevOps.gitlab-ci.yml
    # Image build script
    - project: flap-box/flap
      file: build_image.yml

variables:
    VERSION_SCRIPT: cat ./system/scripts/migrations/base_migration.txt

system_test:
    stage: test
    image: docker:stable
    services: ["docker:dind"]
    script:
        - >
            docker run \
                -it \
                --volume /var/run/docker.sock:/var/run/docker.sock \
                --volume $CI_PROJECT_DIR:$CI_PROJECT_DIR \
                --env FLAP_DIR=$CI_PROJECT_DIR \
                $CI_REGISTRY_IMAGE:$(eval $VERSION_SCRIPT) \
                manager test setup tls

integration_test:
    stage: test
    script:
        - echo "OK"

run_test:
    stage: test
    image: docker:stable
    services: ["docker:dind"]
    script:
        - >
            docker run \
                -it \
                --volume /var/run/docker.sock:/var/run/docker.sock \
                --volume $CI_PROJECT_DIR:$CI_PROJECT_DIR \
                --env FLAP_DIR=$CI_PROJECT_DIR \
                $CI_REGISTRY_IMAGE:$(eval $VERSION_SCRIPT) \
                $FLAP_DIR/system/scripts/start_flap.sh
