include:
    # Auto devop
    - template: Auto-DevOps.gitlab-ci.yml

variables:
    GIT_SUBMODULE_STRATEGY: recursive

# Run start_flap and CLI unit tests
system_test:
    stage: test
    image: docker:stable
    services: ["docker:dind"]
    script:
        # Start a flap instance with mappings to real folders.
        # We need mappings to real folders because docker will resolve its mappings using the real fils system.
        # https://stackoverflow.com/questions/46437147/gitlab-ci-docker-in-docker-cant-create-volume
        - >
            docker run \
                --detach \
            \
                --name flap \
            \
                --env CI=true \
            \
                --volume /var/run/docker.sock:/var/run/docker.sock \
            \
                --volume $CI_PROJECT_DIR:$CI_PROJECT_DIR \
                --volume $CI_BUILDS_DIR/flap_data:$CI_BUILDS_DIR/flap_data \
            \
                --env FLAP_DIR=$CI_PROJECT_DIR \
                --env FLAP_DATA=$CI_BUILDS_DIR/flap_data \
            \
                $CI_REGISTRY_IMAGE/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHA} \
                /bin/sh -c "while true; do sleep 1000; done"

        - docker exec flap manager start
        - docker exec flap manager test setup tls

# Run start_flap then the update procedure
update_test:
    stage: test
    image: docker:stable
    services: ["docker:dind"]
    script:
        # Start a flap instance with mappings to real folders.
        # We need mappings to real folders because docker will resolve its mappings using the real fils system.
        # https://stackoverflow.com/questions/46437147/gitlab-ci-docker-in-docker-cant-create-volume
        - echo $CI_PROJECT_DIR
        - apk add git
        - ls -aslh $CI_PROJECT_DIR
        - ls -aslh $CI_PROJECT_DIR/.git
        - ls -aslh $CI_PROJECT_DIR/.git/refs
        - ls -aslh $CI_PROJECT_DIR/.git/refs/heads
        - git fetch
        - cat $CI_PROJECT_DIR/.git/refs/heads/master
        - >
            docker run \
                --detach \
            \
                --name flap_old \
            \
                --env CI=true \
            \
                --volume /var/run/docker.sock:/var/run/docker.sock \
            \
                --volume $CI_BUILDS_DIR/flap_dir:$CI_BUILDS_DIR/flap_dir \
                --volume $CI_BUILDS_DIR/flap_data:$CI_BUILDS_DIR/flap_data \
            \
                --env FLAP_DIR=$CI_BUILDS_DIR/flap_dir \
                --env FLAP_DATA=$CI_BUILDS_DIR/flap_data \
            \
                $CI_REGISTRY_IMAGE/master:$(cat $CI_PROJECT_DIR/.git/refs/heads/master) \
                /bin/sh -c "while true; do sleep 1000; done"

        # Copy the code to the real folder.
        - docker exec flap_old cp -rT /opt/flap $CI_BUILDS_DIR/flap_dir

        # Update the manager link so it maps to the new location.
        - docker exec flap_old ln -sf $CI_BUILDS_DIR/flap_dir/system/cli/manager.sh /bin/manager

        # Start the instance.
        - docker exec flap_old manager start

        # Update the instance.
        - docker exec flap_old manager update $CI_COMMIT_REF_NAME

integration_test:
    stage: test
    script:
        - echo "OK"
