version: "3"

services:
    # NGINX
    nginx:
        depends_on:
            - seafile
            - sogo
            - core

    # MARIADB
    mariadb:
        build:
            context: ./mariadb
            dockerfile: ./Dockerfile
        ports: ["3306:3306"]

    # POSTGRESQL
    postgres:
        ports: ["5432:5432"]

    # REDIS
    redis:
        ports: ["6379:6379"]

    # MEMCACHED
    memcached:
        ports: ["11211:11211"]

    # LDAP
    ldap:
        build:
            context: ./ldap
            dockerfile: ./Dockerfile
        ports: ["389:389"]

    ldapadmin:
        image: osixia/phpldapadmin
        restart: always
        ports: ["6443:80"]
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: ldap
            PHPLDAPADMIN_HTTPS: "false"
        networks:
            stores-net:

    # FLAP CORE API
    core:
        build:
            context: ./core
            dockerfile: ./Dockerfile
        ports: ["8080:8080", "9230:9229"]
        volumes: ["./core/src:/core/src"]
        entrypoint: ["npm", "run", "serve"]

    # FLAP MANAGER
    manager:
        build:
            context: ./manager
            dockerfile: ./Dockerfile
        ports: ["9229:9229"]
        volumes: ["./manager/src:/manager/src"]

    # SEAFILE
    seafile:
        build:
            context: ./seafile
            dockerfile: ./Dockerfile
        ports: ["8000:8000", "8082:8082"]

    # SOGO
    sogo:
        build:
            context: ./sogo
            dockerfile: ./Dockerfile

networks:
    stores-net:
        internal: false
