version: "3"

services:
    # NGINX
    nginx:
        image: nginx:1.15.8
        restart: always
        volumes:
            - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # NGINX main conf file
            - ./configs/nginx/conf.d:/etc/nginx/conf.d:ro # NGINX sites conf files
            - /etc/ssl/nginx:/etc/ssl/nginx:ro # SSL certificates

            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo # SOGo static files
        depends_on:
            - seafile
            - sogo
        ports: ["80:80", "443:443"]
        networks: [apps-net]

    # MARIADB
    mariadb:
        image: mariadb:10.3
        env_file: [./envs/mariadb.env]
        restart: always
        # ports: ["3306:3306"]
        volumes:
            - ./scripts/mariadb/setup.sql:/docker-entrypoint-initdb.d/setup.sql # Init
            - ./configs/mariadb/my.cnf:/etc/mysql/my.cnf # Config
            - ./data/mariadb:/var/lib/mariadb # Data
        networks:
            stores-net:
                aliases: [mariadb]

    # REDIS
    redis:
        image: redis:5.0
        restart: always
        networks:
            stores-net:
                aliases: [redis]

    # MEMCACHED
    memcached:
        image: memcached:1.5.12
        restart: always
        networks:
            stores-net:
                aliases: [memcached]

    # LDAP
    ldap:
        image: osixia/openldap:1.2.2
        env_file: [./envs/ldap.env]
        restart: always
        ports: ["389:389"]
        volumes:
            - ./data/ldap/config:/etc/ldap/slapd.d # Config
            - ./data/ldap/database:/var/lib/ldap # Data
        networks:
            stores-net:
                aliases: [ldap]

    # SEAFILE
    seafile:
        build:
            context: ./dockerfiles/seafile
            dockerfile: ./Dockerfile
        env_file: [./envs/seafile.env]
        restart: always
        depends_on: [mariadb, ldap]
        volumes:
            - ./data/seafile:/shared # Data
            - ./configs/seafile:/root/conf.addons # Config
        networks:
            stores-net:
            apps-net:
                aliases: [seafile]

    sogo:
        build:
            context: ./dockerfiles/sogo
            dockerfile: ./Dockerfile
        env_file: [./envs/sogo.env]
        restart: always
        depends_on: [mariadb, ldap, memcached]
        volumes:
            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo # Static files needed by nginx
            - ./configs/sogo/sogo.conf:/etc/sogo/sogo.conf # Config
        networks:
            stores-net:
            apps-net:
                aliases: [sogo]

networks:
    apps-net:
    stores-net:
        internal: true

volumes:
    sogoStaticFiles:
        driver: local
