version: "3"

services:
    # NGINX
    nginx:
        image: nginx:1.15.8
        restart: always
        volumes:
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro # [emmc] -> [nginx] NGINX main conf file
            - ./nginx/config/conf.d:/etc/nginx/conf.d:ro # [emmc] -> [nginx] NGINX services conf files
            - ./nginx/config/parts.d:/etc/nginx/parts.d:ro # [emmc] -> [nginx] NGINX parts conf files
            - /etc/ssl/nginx:/etc/ssl/nginx:ro # [emmc] -> [nginx] SSL certificates

            - nextcloudStaticFiles:/var/www/nextcloud:ro # [nextcloud] -> [nginx] Nextcloud static files
            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo:ro # [sogo] -> [nginx] SOGo static files
        depends_on:
            - nextcloud
            - sogo
            - core
        ports: ["80:80", "443:443"]
        networks: [apps-net]

    postgres:
        image: postgres:11.2
        env_file: [./postgres/postgres.env]
        restart: always
        volumes:
            - ./postgres/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro # [emmc] -> [postgres] Init
            - /flap/postgres/data/data:/var/lib/postgresql/data # [postgres] <-> [hd] Data
        networks:
            stores-net:
                aliases: [postgres]

    # REDIS
    redis:
        image: redis:5.0
        restart: always
        volumes:
            - /flap/redis/data:/data # [redis] <-> [hd] Data
        networks:
            stores-net:
                aliases: [redis]

    # MEMCACHED
    memcached:
        image: memcached:1.5.12
        restart: always
        networks:
            stores-net:
                aliases: [memcached]

    # LDAP
    ldap:
        image: registry.gitlab.com/flap-box/ldap:2.4.44
        env_file: [./ldap/ldap.env]
        restart: always
        volumes:
            - ./ldap/prepopulate:/prepopulate:ro # [emmc] -> [ldap] Init
            - /flap/ldap/config:/etc/ldap # [ldap] <-> [hd] Config
            - /flap/ldap/data:/var/lib/ldap # [ldap] <-> [hd] Data
        networks:
            stores-net:
                aliases: [ldap]

    # FLAP CORE API
    core:
        image: registry.gitlab.com/flap-box/core:0.6.9
        env_file: [./core/core.env]
        restart: always
        depends_on: [ldap, redis]
        volumes:
            - /flap/system/data:/var/lib/flap # [hd] <-> [core] Data
        networks:
            stores-net:
            apps-net:
                aliases: [core]

    # NEXTCLOUD
    nextcloud:
        image: nextcloud:16.0.1-fpm
        env_file: [./nextcloud/nextcloud.env]
        restart: always
        depends_on: [postgres, redis, ldap]
        volumes:
            - /flap/nextcloud/data:/data # [nextcloud] <-> [hd] Data
            - /flap/nextcloud/config:/var/www/html/config # [nextcloud] <-> [hd] Config
            - nextcloudStaticFiles:/var/www/html # [nextcloud] -> [nginx] Static files needed by nginx
            - ./nextcloud/scripts/generate_config.sh:/generate_config.sh # [emmc] <-> [nextcloud] Script to generate config.php
        networks:
            stores-net:
            apps-net:
                aliases: [nextcloud]

    # SOGO
    sogo:
        image: registry.gitlab.com/flap-box/sogo:4.0.7
        env_file: [./sogo/sogo.env]
        restart: always
        depends_on: [postgres, ldap, memcached]
        volumes:
            - ./sogo/config/sogo.conf:/etc/sogo/sogo.conf # [emmc] -> [sogo] Config
            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo # [sogo] -> [nginx] Static files needed by nginx
        networks:
            stores-net:
            apps-net:
                aliases: [sogo]

networks:
    apps-net:
    stores-net:
        internal: true

volumes:
    sogoStaticFiles:
    nextcloudStaticFiles:
