version: "3"

services:
    # NGINX
    nginx:
        image: nginx:1.17.1
        container_name: flap_nginx
        restart: always
        volumes:
            # Nginx configurations.
            - ${FLAP_DIR}/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro # [emmc] -> [nginx] NGINX main conf file
            - ${FLAP_DIR}/nginx/config/conf.d:/etc/nginx/conf.d:ro # [emmc] -> [nginx] NGINX services conf files
            - ${FLAP_DIR}/nginx/config/parts.d:/etc/nginx/parts.d:ro # [emmc] -> [nginx] NGINX parts conf files
            # TLS Certificates.
            - /etc/letsencrypt:/etc/letsencrypt:ro # [emmc] -> [nginx] SSL certificates
            # Static files from apps
            - ${FLAP_DIR}/core/src/front/public/logo.svg:/var/www/logo.svg:ro # [emmc] -> [nginx] logo.svg so it can be used by every app.
            - ${FLAP_DATA}/nextcloud/html:/var/www/nextcloud:ro # [nextcloud] -> [nginx] Nextcloud static files
            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo:ro # [sogo] -> [nginx] SOGo static files
            - lemonStaticFiles:/var/www/lemon:ro # [lemon] -> [nginx] Lemon static files.
            - ${FLAP_DIR}/lemon/skin/flapskin:/var/www/lemon_flapskin:ro # [emmc] -> [nginx] Custom scripts and syles for flapskin.
        depends_on:
            - nextcloud
            - sogo
            - core
            - lemon
        ports: ["80:80", "443:443"]
        networks: [apps-net]

    # LEMONLDAP-NG
    lemon:
        image: registry.gitlab.com/flap-box/lemon:2.0.6-1
        container_name: flap_lemon
        env_file: [$FLAP_DIR/lemon/lemon.env]
        restart: always
        volumes:
            - ${FLAP_DIR}/lemon/config/lemonldap-ng.ini:/etc/lemonldap-ng/lemonldap-ng.ini # [emmc] -> [lemon] Main config.
            - ${FLAP_DIR}/lemon/config/lmConf-1.json:/etc/lemonldap-ng/conf/lmConf-1.json # [emmc] -> [lemon] Authentication config.
            - ${FLAP_DIR}/lemon/skin/templates:/usr/share/lemonldap-ng/portal/templates/flapskin # [emmc] -> [lemmon] Custom skin for lemon'sportal.
            - ${FLAP_DATA}/lemon/data:/var/lib/lemonldap-ng # [hd] -> [lemon] LemonLDAP's data.
            - lemonStaticFiles:/usr/ # [lemon] -> [nginx] Lemon static files needed by nginx.
        depends_on: [mail]
        networks:
            stores-net:
            apps-net:
                aliases: [lemon]
                ipv4_address: 172.30.0.100

    # POSTGRESQL
    postgres:
        image: postgres:11.2
        container_name: flap_postgres
        env_file: [$FLAP_DIR/postgres/postgres.env]
        restart: always
        volumes:
            - ${FLAP_DIR}/postgres/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro # [emmc] -> [postgres] Init
            - ${FLAP_DATA}/postgres/data/data:/var/lib/postgresql/data # [postgres] <-> [hd] Data
        networks:
            stores-net:
                aliases: [postgres]

    # REDIS
    redis:
        image: redis:5.0
        container_name: flap_redis
        restart: always
        volumes:
            - ${FLAP_DATA}/redis/data:/data # [redis] <-> [hd] Data
        networks:
            stores-net:
                aliases: [redis]

    # MEMCACHED
    memcached:
        image: memcached:1.5.12
        container_name: flap_memcached
        restart: always
        networks:
            stores-net:
                aliases: [memcached]

    # LDAP
    ldap:
        image: registry.gitlab.com/flap-box/ldap:2.4.47-3
        container_name: flap_ldap
        env_file: [$FLAP_DIR/ldap/ldap.env]
        restart: always
        volumes:
            - ${FLAP_DIR}/ldap/config:/config:ro # [emmc] -> [ldap] Config files to load.
            - ${FLAP_DIR}/ldap/schemas:/schemas:ro # [emmc] -> [ldap] Schemas files to load.
            - ${FLAP_DIR}/ldap/prepopulate:/prepopulate:ro # [emmc] -> [ldap] Entities files to load.
            - ${FLAP_DATA}/ldap/config:/etc/ldap # [ldap] <-> [hd] Config
            - ${FLAP_DATA}/ldap/data:/var/lib/ldap # [ldap] <-> [hd] Data
        networks:
            stores-net:
                aliases: [ldap]

    # MAIL
    mail:
        image: tvial/docker-mailserver:release-v6.2.0
        container_name: flap_mail
        env_file: [./mail/mail.env]
        restart: always
        depends_on: [ldap]
        ports: ["25:25", "143:143", "587:587"]
        volumes:
            - ${FLAP_DATA}/mail/data/mail:/var/mail # [mail] -> [hd] Mail.
            - ${FLAP_DATA}/mail/data/state:/var/mail-state # [mail] -> [hd] State.
            - ${FLAP_DIR}/mail/config/:/tmp/docker-mailserver/ # [emmc] -> [mail] Config.
            - /etc/letsencrypt:/etc/letsencrypt:ro # [emmc] -> [mail] SSL certificates.
        networks:
            stores-net:
            apps-net:
                aliases: [mail]

    # FLAP CORE API
    core:
        image: registry.gitlab.com/flap-box/core:0.9.3
        container_name: flap_core
        env_file: [$FLAP_DIR/core/core.env]
        restart: always
        depends_on: [ldap, redis]
        volumes:
            - ${FLAP_DATA}/system/data:/var/lib/flap # [hd] <-> [core] Data
            - /root/.ssh/authorized_keys:/root/.ssh/authorized_keys # [emmc] <-> [core] SSH authorized keys
        networks:
            stores-net:
            apps-net:
                aliases: [core]

    # NEXTCLOUD
    nextcloud:
        image: nextcloud:17.0.1-fpm
        container_name: flap_nextcloud
        env_file: [$FLAP_DIR/nextcloud/nextcloud.env]
        restart: always
        depends_on: [postgres, redis, ldap, mail]
        volumes:
            - ${FLAP_DATA}/nextcloud/saml:/saml/nextcloud # [hd] -> [nextcloud] nextcloud's SAML keys.
            - ${FLAP_DATA}/lemon/saml:/saml/idp # [hd] -> [nextcloud] IDP's SAML keys.
            - ${FLAP_DATA}/nextcloud/data:/data # [nextcloud] <-> [hd] Data
            - ${FLAP_DATA}/nextcloud/config:/var/www/html/config # [nextcloud] <-> [hd] Config
            - ${FLAP_DATA}/nextcloud/html:/var/www/html # [nextcloud] <-> [hd] WWW
            - ${FLAP_DIR}/nextcloud/scripts/generate_config.sh:/generate_config.sh # [emmc] <-> [nextcloud] Script to generate config.php
        networks:
            stores-net:
            apps-net:
                aliases: [nextcloud]

    # SOGO
    sogo:
        image: registry.gitlab.com/flap-box/sogo:4.1.1-1
        container_name: flap_sogo
        env_file: [$FLAP_DIR/sogo/sogo.env]
        restart: always
        depends_on: [postgres, ldap, memcached, mail]
        volumes:
            - ${FLAP_DIR}/sogo/config/sogo.conf:/etc/sogo/sogo.conf # [emmc] -> [sogo] SOGo's config.
            - ${FLAP_DIR}/sogo/config/stunnel.conf:/etc/stunnel/sogo.conf # [emmc] -> [sogo] Stunnel's config.
            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo # [sogo] -> [nginx] Static files needed by nginx
        networks:
            stores-net:
            apps-net:
                aliases: [sogo]

networks:
    apps-net:
        ipam:
            config:
                - subnet: 172.30.0.0/24
    stores-net:
        internal: true

volumes:
    sogoStaticFiles:
    nextcloudStaticFiles:
    lemonStaticFiles:
