version: "3"

services:
    # NGINX
    nginx:
        image: nginx:1.15.8
        restart: always
        volumes:
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro # NGINX main conf file
            - ./nginx/config/conf.d:/etc/nginx/conf.d:ro # NGINX sites conf files
            - /etc/ssl/nginx:/etc/ssl/nginx:ro # SSL certificates

            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo # SOGo static files
        depends_on:
            - seafile
            - sogo
            - core
        ports: ["80:80", "443:443"]
        networks: [apps-net]

    # MARIADB
    mariadb:
        image: mariadb:10.3
        env_file: [./mariadb/mariadb.env]
        restart: always
        # ports: ["3306:3306"]
        volumes:
            - ./mariadb/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql # Init
            - ./mariadb/config/my.cnf:/etc/mysql/my.cnf # Config
            - ./mariadb/data:/var/lib/mysql # Data
        networks:
            stores-net:
                aliases: [mariadb]

    # REDIS
    redis:
        image: redis:5.0
        restart: always
        volumes:
            - ./redis/data:/data # Data
        networks:
            stores-net:
                aliases: [redis]

    # MEMCACHED
    memcached:
        image: memcached:1.5.12
        restart: always
        networks:
            stores-net:
                aliases: [memcached]

    # LDAP
    ldap:
        build:
            context: ./ldap
            dockerfile: ./image/Dockerfile
        env_file: [./ldap/ldap.env]
        restart: always
        # ports: ["389:389"]
        volumes:
            - ./ldap/prepopulate:/prepopulate:ro # Init
            - ./ldap/data/config:/etc/ldap # Config
            - ./ldap/data/data:/var/lib/ldap # Data
        networks:
            stores-net:
                aliases: [ldap]
    # DEV MODE
    # ldapadmin:
    #     image: osixia/phpldapadmin
    #     restart: always
    #     ports: ["6443:80"]
    #     environment:
    #         PHPLDAPADMIN_LDAP_HOSTS: ldap
    #         PHPLDAPADMIN_HTTPS: "false"
    #     networks:
    #         stores-net:

    # FLAP CORE
    core:
        build:
            context: ./core
            dockerfile: ./image/Dockerfile
        env_file: [./core/core.env]
        restart: always
        depends_on: [ldap, redis]
        networks:
            stores-net:
            apps-net:
                aliases: [core]
        # DEV MODE
        # ports: ["8080:8080", "9229:9229"]
        # volumes: ["./core:/flap"]
        # entrypoint: ["npm", "run", "serve"]

    # SEAFILE
    seafile:
        build:
            context: ./seafile/image
            dockerfile: ./Dockerfile
        env_file: [./seafile/seafile.env]
        restart: always
        depends_on: [mariadb, ldap]
        depends_on: [mariadb, ldap, memcached]
        volumes:
            - ./seafile/data:/shared # Data
            - ./seafile/config:/conf.addons # Config
        networks:
            stores-net:
            apps-net:
                aliases: [seafile]

    # SOGO
    sogo:
        build:
            context: ./sogo/image
            dockerfile: ./Dockerfile
        env_file: [./sogo/sogo.env]
        restart: always
        depends_on: [mariadb, ldap, memcached]
        volumes:
            - ./sogo/config/sogo.conf:/etc/sogo/sogo.conf # Config
            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo # Static files needed by nginx
        networks:
            stores-net:
            apps-net:
                aliases: [sogo]

networks:
    apps-net:
    stores-net:
        internal: true

volumes:
    sogoStaticFiles:
