version: "3"

services:
    # NGINX
    nginx:
        image: nginx:1.15.8
        restart: always
        volumes:
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro # NGINX main conf file
            - ./nginx/config/conf.d:/etc/nginx/conf.d:ro # NGINX sites conf files
            - ./nginx/config/parts.d:/etc/nginx/parts.d:ro # NGINX parts conf files
            - /etc/ssl/nginx:/etc/ssl/nginx:ro # SSL certificates

            - nextcloudStaticFiles:/var/www/nextcloud:ro # Nextcloud static files
            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo:ro # SOGo static files
        depends_on:
            - nextcloud
            - sogo
            - core
        ports: ["80:80", "443:443"]
        networks: [apps-net]

    postgres:
        image: postgres:11.2
        env_file: [./postgres/postgres.env]
        restart: always
        volumes:
            - ./postgres/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql # Init
            - ./postgres/data:/var/lib/postgresql/data # Data
        networks:
            stores-net:
                aliases: [postgres]

    # REDIS
    redis:
        image: redis:5.0
        restart: always
        volumes:
            - ./redis/data:/data # Data
        networks:
            stores-net:
                aliases: [redis]

    # MEMCACHED
    memcached:
        image: memcached:1.5.12
        restart: always
        networks:
            stores-net:
                aliases: [memcached]

    # LDAP
    ldap:
        image: registry.gitlab.com/flap-box/ldap:2.4.44
        env_file: [./ldap/ldap.env]
        restart: always
        volumes:
            - ./ldap/prepopulate:/prepopulate:ro # Init
            - ./ldap/data/config:/etc/ldap # Config
            - ./ldap/data/data:/var/lib/ldap # Data
        networks:
            stores-net:
                aliases: [ldap]

    # FLAP CORE API
    core:
        image: registry.gitlab.com/flap-box/core:0.5.7
        env_file: [./core/core.env]
        restart: always
        depends_on: [ldap, redis]
        volumes:
            - /var/lib/flap:/var/lib/flap # Manager's data
        networks:
            stores-net:
            apps-net:
                aliases: [core]

    # NEXTCLOUD
    nextcloud:
        image: nextcloud:15.0.6-fpm
        env_file: [./nextcloud/nextcloud.env]
        restart: always
        depends_on: [postgres, redis, ldap]
        volumes:
            - ./nextcloud/data:/data # Data
            - nextcloudStaticFiles:/var/www/html # Static files needed by nginx
            - ./nextcloud/scripts/setup.sh:/setup.sh # Setup script
        networks:
            stores-net:
            apps-net:
                aliases: [nextcloud]

    # SOGO
    sogo:
        image: registry.gitlab.com/flap-box/sogo:4.0.7
        env_file: [./sogo/sogo.env]
        restart: always
        depends_on: [postgres, ldap, memcached]
        volumes:
            - ./sogo/config/sogo.conf:/etc/sogo/sogo.conf # Config
            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo # Static files needed by nginx
        networks:
            stores-net:
            apps-net:
                aliases: [sogo]

networks:
    apps-net:
    stores-net:
        internal: true

volumes:
    sogoStaticFiles:
    nextcloudStaticFiles:
