version: "3"

services:
    # NGINX
    nginx:
        image: nginx:1.15.8
        restart: always
        volumes:
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro # NGINX main conf file
            - ./nginx/config/conf.d:/etc/nginx/conf.d:ro # NGINX sites conf files
            - ./nginx/config/parts.d:/etc/nginx/parts.d:ro # NGINX parts conf files
            - tlsCertificates:/etc/ssl/nginx:ro # SSL certificates

            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo # SOGo static files
        depends_on:
            - seafile
            - sogo
            - core
        ports: ["80:80", "443:443"]
        networks: [apps-net]

    # MARIADB
    mariadb:
        image: mariadb:10.3
        env_file: [./mariadb/mariadb.env]
        restart: always
        volumes:
            - ./mariadb/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql # Init
            - ./mariadb/config/my.cnf:/etc/mysql/my.cnf # Config
            - ./mariadb/data:/var/lib/mysql # Data
        networks:
            stores-net:
                aliases: [mariadb]

    # REDIS
    redis:
        image: redis:5.0
        restart: always
        volumes:
            - ./redis/data:/data # Data
        networks:
            stores-net:
                aliases: [redis]

    # MEMCACHED
    memcached:
        image: memcached:1.5.12
        restart: always
        networks:
            stores-net:
                aliases: [memcached]

    # LDAP
    ldap:
        image: registry.gitlab.com/flap-box/ldap:2.4.44
        env_file: [./ldap/ldap.env]
        restart: always
        # ports: ["389:389"]
        volumes:
            - ./ldap/prepopulate:/prepopulate:ro # Init
            - ./ldap/data/config:/etc/ldap # Config
            - ./ldap/data/data:/var/lib/ldap # Data
        networks:
            stores-net:
                aliases: [ldap]

    # FLAP CORE API
    core:
        image: registry.gitlab.com/flap-box/core:0.3.1
        env_file: [./core/core.env]
        restart: always
        depends_on: [ldap, redis]
        networks:
            stores-net:
            apps-net:
                aliases: [core]

    # FLAP MANAGER
    manager:
        image: registry.gitlab.com/flap-box/manager:0.2.0
        # Needed for UPnP
        network_mode: host
        volumes:
            - ./:/flap # Bind the whole FLAP directory so we can generate some config
            - ./manager/data:/var/lib/manager # Manager's data
            - /var/run/docker.sock:/var/run/docker.sock # Bind docker sock so manager can manage docker
            - tlsCertificates:/etc/ssl/nginx # SSL certificates

    # SEAFILE
    seafile:
        image: registry.gitlab.com/flap-box/seafile:6.3.4
        env_file: [./seafile/seafile.env]
        restart: always
        depends_on: [mariadb, ldap, memcached]
        volumes:
            - ./seafile/data:/shared # Data
            - ./seafile/config:/conf # Config
        networks:
            stores-net:
            apps-net:
                aliases: [seafile]

    # SOGO
    sogo:
        image: registry.gitlab.com/flap-box/sogo:4.0.7
        restart: always
        depends_on: [mariadb, ldap, memcached]
        volumes:
            - ./sogo/config/sogo.conf:/etc/sogo/sogo.conf # Config
            - sogoStaticFiles:/usr/local/lib/GNUstep/SOGo # Static files needed by nginx
        networks:
            stores-net:
            apps-net:
                aliases: [sogo]

networks:
    apps-net:
    stores-net:
        internal: true

volumes:
    sogoStaticFiles:
    tlsCertificates:
