.build_docker:
    stage: build
    only: [master]
    image: docker:stable
    services: ["docker:dind"]
    script:
        - DOCKER_DRIVER=overlay2
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
        - docker build --tag $CI_REGISTRY_IMAGE:$ARCH-$(eval $VERSION_SCRIPT) --tag $CI_REGISTRY_IMAGE:$ARCH-latest .
        - docker push $CI_REGISTRY_IMAGE

.build_adm64:
    extends: .build_docker
    tags: [docker, gce]
    variables:
        ARCH: amd64

.build_armv7:
    extends: .build_docker
    tags: [docker, odroid]
    variables:
        ARCH: armv7

create_manifest:
    dependencies: ["build:amd64", "build:armv7"]
    script:
        - docker manifest create \
            $CI_REGISTRY_IMAGE:$(eval $VERSION_SCRIPT) \
            $CI_REGISTRY_IMAGE:amd64-$(eval $VERSION_SCRIPT) \
            $CI_REGISTRY_IMAGE:armv7-$(eval $VERSION_SCRIPT)
        - docker manifest create \
            $CI_REGISTRY_IMAGE:latest \
            $CI_REGISTRY_IMAGE:amd64-latest \
            $CI_REGISTRY_IMAGE:armv7-latest
        - docker manifest push $CI_REGISTRY_IMAGE:$(eval $VERSION_SCRIPT)
        - docker manifest push $CI_REGISTRY_IMAGE:latest
