#!/bin/bash

set -euo pipefail


FLAP_ENV_VARS="$FLAP_ENV_VARS \${LEMON_ENABLE_REGISTRATIONS} \${LEMON_REGISTRATIONS}"
SUBDOMAINS="$SUBDOMAINS auth"

export LEMON_ENABLE_REGISTRATIONS
export LEMON_REGISTRATIONS

if [ "${FLAG_ALLOW_REGISTRATIONS:-}" == "true" ]
then
	LEMON_ENABLE_REGISTRATIONS=1
	LEMON_REGISTRATIONS=LDAP
else
	LEMON_ENABLE_REGISTRATIONS=0
	LEMON_REGISTRATIONS=Null
fi
