services:
    prometheus:
        image: prom/prometheus:v2.23.0
        container_name: flap_prometheus
        volumes:
            - ${FLAP_DIR}/monitoring/config/prometheus:/etc/prometheus
            - prometheus_data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/consoles"
            - "--storage.tsdb.retention.time=200h"
            - "--web.enable-lifecycle"
        restart: unless-stopped
        logging:
            driver: ${LOG_DRIVER:-journald}
        expose: [9090]
        networks:
            monitor-net:
                aliases: [prometheus]
        labels:
            org.label-schema.group: "monitoring"

    alertmanager:
        image: prom/alertmanager:v0.21.0
        container_name: flap_alertmanager
        volumes:
            - ${FLAP_DIR}/monitoring/config/alertmanager:/etc/alertmanager
        command:
            - "--config.file=/etc/alertmanager/config.yml"
            - "--storage.path=/alertmanager"
        restart: unless-stopped
        logging:
            driver: ${LOG_DRIVER:-journald}
        expose: [9093]
        networks:
            monitor-net:
                aliases: [alertmanager]
        labels:
            org.label-schema.group: "monitoring"

    grafana:
        image: grafana/grafana:7.3.4
        container_name: flap_grafana
        volumes:
            - grafana_data:/var/lib/grafana
            - ${FLAP_DIR}/monitoring/config/grafana/provisioning:/etc/grafana/provisioning
            - ${FLAP_DIR}/monitoring/config/grafana/dashboards:/etc/grafana/dashboards
        env_file: [$FLAP_DIR/monitoring/grafana.env]
        restart: unless-stopped
        logging:
            driver: ${LOG_DRIVER:-journald}
        expose: [3000]
        networks:
            monitor-net:
            apps-net:
                aliases: [grafana]
        labels:
            org.label-schema.group: "monitoring"

    pushgateway:
        image: prom/pushgateway:v1.3.0
        container_name: flap_pushgateway
        restart: unless-stopped
        logging:
            driver: ${LOG_DRIVER:-journald}
        expose: [9091]
        networks:
            monitor-net:
                aliases: [pushgateway]
        labels:
            org.label-schema.group: "monitoring"

networks:
    monitor-net:
        name: flap_stores-net
        internal: true

volumes:
    prometheus_data: {}
    grafana_data: {}
