#!/bin/bash

set -eu

FLAP_ENV_VARS="$FLAP_ENV_VARS \${ENABLE_MONITORING}"
SUBDOMAINS="$SUBDOMAINS monitoring"

export ENABLE_MONITORING

ENABLE_MONITORING=$(yq .monitoring.enable "$FLAP_DATA/system/flap.yml")
ENABLE_MONITORING=${ENABLE_MONITORING:-false}
