#!/bin/bash

set -euo pipefail


# shellcheck disable=SC2016
FLAP_ENV_VARS="$FLAP_ENV_VARS \${FLAG_DISABLE_ADVANCED_SETTINGS}"
SUBDOMAINS="$SUBDOMAINS home"

export FLAG_DISABLE_ADVANCED_SETTINGS
FLAG_DISABLE_ADVANCED_SETTINGS=${FLAG_DISABLE_ADVANCED_SETTINGS:-false}
