services:
    nextcloud:
        # Check "Critical changes..." issue before updating the version number.
        # https://github.com/nextcloud/server/issues?q=Critical+changes
        image: nextcloud:18.0.6-fpm
        container_name: flap_nextcloud
        env_file: [$FLAP_DIR/nextcloud/nextcloud.env]
        restart: unless-stopped
        logging:
            driver: ${LOG_DRIVER:-journald}
        depends_on: [postgres, redis, ldap]
        volumes:
            - ${FLAP_DATA}/nextcloud/saml:/saml/nextcloud # [hd] -> [nextcloud] nextcloud's SAML keys.
            - ${FLAP_DATA}/lemon/saml:/saml/idp # [hd] -> [nextcloud] IDP's SAML keys.
            - ${FLAP_DATA}/nextcloud/data:/data # [nextcloud] <-> [hd] Data
            - ${FLAP_DATA}/nextcloud/config:/var/www/html/config # [nextcloud] <-> [hd] Config
            - ${FLAP_DATA}/nextcloud/html:/var/www/html # [nextcloud] <-> [hd] WWW
            - ${FLAP_DIR}/nextcloud/scripts/inner_scripts:/inner_scripts # [emmc] <-> [nextcloud] Script to generate config.php
        networks:
            stores-net:
            apps-net:
                aliases: [nextcloud]

x-nginx-extra-volumes:
    - ${FLAP_DATA}/nextcloud/html:/var/www/nextcloud:ro # [emmc] -> [nginx] Nextcloud static files.
    - ${FLAP_DIR}/nextcloud/medias:/var/www/nextcloud_medias:ro # [emmc] -> [nginx] Other Nextcloud static files.
