services:
    image: collabora/code:latest
    collabora:
        container_name: flap_collabora
        env_file: [$FLAP_DIR/collabora/collabora.env]
        restart: unless-stopped
        logging:
            driver: ${LOG_DRIVER:-journald}
        networks:
            apps-net:
                aliases: [collabora]
        # cap_add:
        # - MKNOD