#!/bin/bash

set -eu

FLAP_ENV_VARS="$FLAP_ENV_VARS \${NEXTCLOUD_DB_PWD} \${FLAG_NO_DOCUMENTSERVER}"
SUBDOMAINS="$SUBDOMAINS files"

export ENABLE_NEXTCLOUD
export NEXTCLOUD_DB_PWD
export FLAG_NO_DOCUMENTSERVER

ENABLE_NEXTCLOUD=${ENABLE_NEXTCLOUD:-true}

NEXTCLOUD_DB_PWD=$(generatePassword nextcloud nextcloud_db_pwd)

FLAG_NO_DOCUMENTSERVER=${FLAG_NO_DOCUMENTSERVER:-false}
