services:
    nodeexporter:
        image: prom/node-exporter:v1.0.1
        container_name: flap_nodeexporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - "--path.procfs=/host/proc"
            - "--path.rootfs=/rootfs"
            - "--path.sysfs=/host/sys"
            - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
        restart: always
        logging:
            driver: ${LOG_DRIVER:-journald}
        expose: [9100]
        networks:
            monitor-net:
                aliases: [nodeexporter]
        labels:
            org.label-schema.group: "monitoring"

    cadvisor:
        image: gcr.io/google-containers/cadvisor:v0.36.0
        container_name: flap_cadvisor
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro
            - /cgroup:/cgroup:ro
        restart: always
        logging:
            driver: ${LOG_DRIVER:-journald}
        expose: [8080]
        networks:
            monitor-net:
                aliases: [cadvisor]
        labels:
            org.label-schema.group: "monitoring"
