version: "3.7"

services:
    memcached:
        image: memcached:1.5.12
        container_name: flap_memcached
        restart: always
        networks:
            stores-net:
                aliases: [memcached]

networks:
    stores-net:
        internal: false
