# Version 2.x is more approriate for our use case.
# See: https://github.com/docker/compose/issues/4513#issuecomment-377311337
version: "2.4"

services:
    # Check release notes here: https://github.com/memcached/memcached/wiki/ReleaseNotes
    memcached:
        image: memcached:1.6.5
        container_name: flap_memcached
        restart: unless-stopped
        logging:
            driver: ${LOG_DRIVER:-journald}
        networks:
            stores-net:
                aliases: [memcached]

networks:
    apps-net:
        name: flap_apps-net
    stores-net:
        name: flap_stores-net
        internal: true
