env_vars:
    FLAG_NO_CLEAN_DOCKER: true
    FLAG_NO_NAT_NETWORK_SETUP: true
    FLAG_NO_CRON_SETUP: true
    FLAG_NO_TLS_GENERATION: true
    FLAG_LOCALHOST_TLS_INSTALL: true
    FLAG_GENERATE_DOCKER_COMPOSE_OVERRIDE: true
    FLAG_NO_FIREWALL_SETUP: true
