services:
    peertube:
        image: chocobozzz/peertube:v4.3.1-bullseye
        container_name: flap_peertube
        # 1935: live video port
        ports: [ "1935:1935" ]
        env_file: [ $FLAP_DIR/peertube/peertube.env ]
        restart: unless-stopped
        logging:
            driver: ${LOG_DRIVER:-journald}
        depends_on: [ postgres, redis, ldap, mail ]
        volumes:
            - ${FLAP_DATA}/peertube/data:/data # [peertube] <-> [hd] Users' data.
            - ${FLAP_DATA}/peertube/config:/config # [peertube] <-> [emmc] Config files.
            - peertubeStaticFiles:/app/client/dist # [peertube] <-> [nginx] Static files needed by nginx.
        networks:
            stores-net: null
            apps-net:
                aliases: [ peertube ]

volumes:
    peertubeStaticFiles:
        name: flap_peertubeStaticFiles

x-nginx-extra-volumes:
    - peertubeStaticFiles:/var/www/peertube/peertube-latest/client/dist:ro # [peertube] -> [nginx] Peertube static files.
    - ${FLAP_DATA}/peertube/data:/var/www/peertube_data:ro # [emmc] -> [nginx] Peertube's users content.
    - ${FLAP_DIR}/peertube/medias:/var/www/peertube_medias:ro # [emmc] -> [nginx] Peertube static files.
