services:
    matomo:
        image: matomo:3.14-fpm
        container_name: flap_matomo
        env_file: [$FLAP_DIR/matomo/matomo.env]
        restart: unless-stopped
        logging:
            driver: ${LOG_DRIVER:-journald}
        depends_on: [mariadb, ldap]
        volumes:
            - ${FLAP_DATA}/matomo/html:/var/www/html # [matomo] <-> [hd] WWW
            - ${FLAP_DIR}/matomo/scripts/inner_scripts:/inner_scripts # [emmc] <-> [matomo] Script to generate config.php
        networks:
            stores-net:
            apps-net:
                aliases: [matomo]

volumes:
    matomoStaticFiles:
        name: flap_matomoStaticFiles

x-nginx-extra-volumes:
    - ${FLAP_DATA}/matomo/html:/var/www/matomo:ro # [emmc] -> [nginx] Matomo static files.
    - ${FLAP_DIR}/matomo/medias:/var/www/matomo_medias:ro # [emmc] -> [nginx] Matomo static files.
