services:
    mail:
        image: mailserver/docker-mailserver:12.0
        container_name: flap_mail
        env_file: [ ./mail/mail.env ]
        restart: unless-stopped
        logging:
            driver: ${LOG_DRIVER:-journald}
        depends_on: [ ldap ]
        ports: [ "25:25", "143:143", "587:587" ]
        cap_add: [ NET_ADMIN ]
        stop_grace_period: 1m
        healthcheck:
            test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
            timeout: 3s
            retries: 0
        networks:
            stores-net: null
            apps-net:
                aliases: [ mail ]

x-mail-extra-volumes:
    - ${FLAP_DATA}/mail/data/mail:/var/mail # [mail] -> [hd] Mail.
    - ${FLAP_DATA}/mail/data/state:/var/mail-state # [mail] -> [hd] State.
    - ${FLAP_DIR}/mail/config/:/tmp/docker-mailserver/ # [emmc] -> [mail] Config.
    - /etc/letsencrypt:/etc/letsencrypt:ro # [emmc] -> [mail] SSL certificates.
