#!/bin/bash

set -eu

FLAP_ENV_VARS="$FLAP_ENV_VARS \${PEERTUBE_DB_PWD} \${PEERTUBE_DOMAIN_NAME} \${PEERTUBE_SAML_PLUGIN_VERSION}"
SUBDOMAINS="$SUBDOMAINS video"

# 1935 - Live streaming
NEEDED_PORTS="$NEEDED_PORTS 1935/tcp"

export PEERTUBE_DB_PWD
export PEERTUBE_SAML_PLUGIN_VERSION

PEERTUBE_DB_PWD=$(generatePassword peertube peertube_db_pwd)
PEERTUBE_SAML_PLUGIN_VERSION=0.0.4