services:
    postgres:
        image: postgres:11.2
        container_name: flap_postgres
        env_file: [$FLAP_DIR/postgres/postgres.env]
        restart: always
        volumes:
            - ${FLAP_DIR}/postgres/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro # [emmc] -> [postgres] Init
            - ${FLAP_DATA}/postgres/data/data:/var/lib/postgresql/data # [postgres] <-> [hd] Data
        networks:
            stores-net:
                aliases: [postgres]
