services:
    postgres:
        # Do not upgrade lightly. See:
        # Github issue for automatic upgrade in docker container: https://github.com/docker-library/postgres/issues/37
        # pg_upgrade doc: https://www.postgresql.org/docs/9.4/pgupgrade.html
        image: postgres:11.7
        container_name: flap_postgres
        env_file: [$FLAP_DIR/postgres/postgres.env]
        restart: always
        logging:
            driver: ${LOG_DRIVER:-journald}
        volumes:
            - ${FLAP_DIR}/postgres/scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro # [emmc] -> [postgres] Init
            - ${FLAP_DATA}/postgres/data/data:/var/lib/postgresql/data # [postgres] <-> [hd] Data
        networks:
            stores-net:
                aliases: [postgres]
