services:
    redis:
        # Check release notes here: https://redis.io/download
        image: redis:6.0
        container_name: flap_redis
        restart: always
        logging:
            driver: ${LOG_DRIVER:-journald}
        volumes:
            - ${FLAP_DATA}/redis/data:/data # [redis] <-> [hd] Data
        networks:
            stores-net:
                aliases: [redis]
